services:
  - type: web
    name: object-detection
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python download_model.py"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
